// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_pokemon_id_ from "./routes/api/pokemon/[id].ts";
import * as $index from "./routes/index.tsx";
import * as $pokemon_list_page_ from "./routes/pokemon-list/[page].tsx";
import * as $pokemon_id_ from "./routes/pokemon/[id].tsx";
import * as $SerchForm from "./islands/SerchForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/pokemon/[id].ts": $api_pokemon_id_,
    "./routes/index.tsx": $index,
    "./routes/pokemon-list/[page].tsx": $pokemon_list_page_,
    "./routes/pokemon/[id].tsx": $pokemon_id_,
  },
  islands: {
    "./islands/SerchForm.tsx": $SerchForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
